image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run Movie app

ports:
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack